package translator;

public enum OptionsOfAction {

	checkNAMEParmenent,
	INITIALIZE_COMBO_BOX,
	UPDATEPERMANENT,
	DELETEPERMANENT,
	checkDB,
	CURRENT_IN_ROLE,
	LOGIN, 
	GETRELATEDREQUESTS,
	 NEWREQUEST, 
	 GET_APPRAISER_AND_PERFORMANCE_LEADER_CB_DATA,
	APPOINT_APPRAISER_OR_PERFORMANCE_LEADER,
	 SET_EVALUATION_OR_EXECUTION_DUE_TIME,
	GETALLPROCESSES, 
	GETALLINFORMATIONSYSTEMS,
	GET_APPRAISER_AND_PERFORMANCE_LEADER_OF_PROC,
	ADD_EVALUATION_OR_EXECUTION_EXTENSION_TIME,
	FREEZE_PROCESS,
	DEFROST_PROCESS,
	SHUTDOWN_PROCESS;
	
	
	
	
	
	


}



/* GETALLINFORMATIONSYSTEMS - is an option that is currently NOT in use.
 * If it will be in use, it will be for the NewRequestController.
 * Maybe if we would like to get all the information Systems from the database.
 */
