package translator;

public enum OptionsOfAction {

	SELECTCHAIRMAN,
	UPDATEPERMANENT,
	DELETEPERMANENT,
	checkDB,
	LOGIN,
	GETRELATEDREQUESTS,
	NEWREQUEST,
	GET_APPRAISER_AND_PERFORMANCE_LEADER_CB_DATA,
	APPOINT_APPRAISER_OR_PERFORMANCE_LEADER,
	GET_APPRAISER_AND_PERFORMANCE_LEADER_OF_PROC,
	SET_EVALUATION_OR_EXECUTION_DUE_TIME,
	ADD_EVALUATION_OR_EXECUTION_EXTENSION_TIME,
	GETALLPROCESSES,
	GETALLINFORMATIONSYSTEMS,
	FREEZE_PROCESS,
	DEFROST_PROCESS,
	SHUTDOWN_PROCESS,
	INSERT_FAILURE_REPORT

}



/* GETALLINFORMATIONSYSTEMS - is an option that is currently NOT in use.
 * If it will be in use, it will be for the NewRequestController.
 * Maybe if we would like to get all the information Systems from the database.
 */
