package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import java.sql.DriverManager;

import javafx.scene.control.Alert.AlertType;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.net.URL;
import java.sql.Connection;
import client.Client;
import java.util.ArrayList;
import java.util.ResourceBundle;

import com.sun.xml.internal.ws.org.objectweb.asm.Label;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.concurrent.Worker;
import javafx.concurrent.WorkerStateEvent;
import javafx.event.ActionEvent;
import java.sql.ResultSet;


import javafx.scene.control.ComboBox;
import javafx.scene.text.Text;
import javafx.scene.control.Alert.AlertType;
import translator.OptionsOfAction;
import translator.Translator;


public class StaffMainController implements Initializable{
	
	Client client = Client.getInstance();
	public static StaffMainController instance;
	PreparedStatement stmt;
	private static Connection conn;
	@FXML
	private Button back_btn;
    @FXML
    private Text print_message;
	@FXML
	private Button AppointCangesControlBoard;
	@FXML
	private ComboBox<String>  chairman_comboBox;
	@FXML
	private ComboBox firstIE_comboBox;
	@FXML
	private ComboBox secondIE_comboBox;
	@FXML
	private ComboBox supervisor_comboBox;
	@FXML
	private Button AppointSupervisor;
	@FXML
	private Button log_out_btn;
	private ArrayList<String> IDChosenStaff= new ArrayList<String>();
	private ArrayList<String> FullNameChosenStaff= new ArrayList<String>();
	ArrayList<String> workersList = new ArrayList<String>();
	// Event Listener on Button[#back_btn].onAction
	@FXML
	public void back_click(ActionEvent event) {
   // 	ScreenController.getScreenController().activate(ScreenController.getScreenController().getLastScreen());
	}
	// Event Listener on Button[#AppointCangesControlBoard].onAction
	@FXML
    void AppointsecondIEclick(ActionEvent event) {

    }
    @FXML
    void AppointfirstIEclick(ActionEvent event) {

    }


	@FXML
	public void Appoint_Chiarman_click(ActionEvent event)
	{
		ArrayList<Object> params = new ArrayList<Object>();
		
		String name =chairman_comboBox.getValue();
		System.out.println(name);
		for(int i=0;i<FullNameChosenStaff.size();i++)
			if(FullNameChosenStaff.get(i).equals(name))//find the name in array and get his id
			{
				params.add(IDChosenStaff.get(i));
			}
		params.add("ChairMan");
		
		Translator translator = new Translator(OptionsOfAction.UPDATEPERMANENT, params);
		Client.getInstance().handleMessageFromClientGUI(translator);
	}
	// Event Listener on Button[#AppointSupervisor].onAction
	@FXML
	public void AppointSupervisor_click(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub

		instance = this;	
		print_message.setVisible(false);
	}
	public void getChairManData() {
		try {
			print_message.setVisible(false);
		ArrayList<String> check= new ArrayList<String>();
		Translator translator= new Translator(OptionsOfAction.SELECTCHAIRMAN,check);
		client/*Client.getInstance()*/.handleMessageFromClientGUI(translator);
	}
		catch(Exception e){}
	}
	
	public void setDataChairMan(ArrayList<String> WorkersName)
	{
		print_message.setVisible(false);
		ObservableList<String> data = FXCollections.observableArrayList();
		
		System.out.println("WorkersName"+WorkersName);
		for (int i=0;i<WorkersName.size()/3;i++) { // get the processID from the Select query
			
			data.add(new String (WorkersName.get(i*3)+" "+WorkersName.get(i*3+1)));
			this.IDChosenStaff.add(new String(WorkersName.get(i*3+2)));
			}
		System.out.println(IDChosenStaff);
		chairman_comboBox.setItems(data);
		this.FullNameChosenStaff.addAll(data);
		System.out.println(FullNameChosenStaff);

	}
	public void printMessage(ArrayList<String> WorkersName)
	{	print_message.setVisible(true);
		print_message.setText(WorkersName.get(0)+" " +WorkersName.get(1)+"is now: "+WorkersName.get(2));
	}
	

    
}
